/**
 * Generate the API's runtime config from the devnet deploy manifest.
 *
 * The deploy script `new`-deploys the Core-6 tokens, so their addresses are whatever the chain
 * assigned — the checked-in `tokens.devnet.json` (mainnet addresses) does not describe a local
 * devnet. Both artifacts below are generated per-deploy and stay untracked.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

import { readManifest, REPO_ROOT, type Manifest } from "../lib/manifest.ts";

const TOKENS_OUT = resolve(REPO_ROOT, "devnet/generated/tokens.json");
const CONFIG_OUT = resolve(REPO_ROOT, "solvent.toml");

// Symbol -> token-list tag, mirroring the checked-in list's grouping.
const TAGS: Record<string, string> = {
  WETH: "majors",
  WBTC: "majors",
  USDC: "stables",
  USDT: "stables",
  DAI: "stables",
  LINK: "defi",
};

// Binance feed symbol -> the devnet token it prices. USDT has no pair; it is the peg instead.
const PRICE_FEEDS: Record<string, string> = {
  ETHUSDT: "WETH",
  BTCUSDT: "WBTC",
  USDCUSDT: "USDC",
  DAIUSDT: "DAI",
  LINKUSDT: "LINK",
};

const NAMES: Record<string, string> = {
  WETH: "Wrapped Ether",
  WBTC: "Wrapped BTC",
  USDC: "USD Coin",
  USDT: "Tether USD",
  DAI: "Dai Stablecoin",
  LINK: "ChainLink Token",
};

function tokenList(manifest: Manifest) {
  return {
    name: "Solvent Devnet",
    version: { major: 1, minor: 0, patch: 0 },
    tokens: Object.entries(manifest.tokens).map(([symbol, token]) => ({
      chainId: manifest.chain_id,
      address: token.address,
      symbol,
      name: NAMES[symbol] ?? symbol,
      decimals: token.decimals,
      tags: [TAGS[symbol] ?? "other"],
    })),
  };
}

function address(manifest: Manifest, symbol: string): string {
  const token = manifest.tokens[symbol];
  if (!token) throw new Error(`manifest has no ${symbol} token`);
  return token.address;
}

function configToml(manifest: Manifest, tokenListPath: string): string {
  const feeds = Object.entries(PRICE_FEEDS)
    .filter(([, symbol]) => manifest.tokens[symbol])
    .map(([feed, symbol]) => `[[price_symbols]]\nsymbol = "${feed}"\ntokens = ["${address(manifest, symbol)}"]  # ${symbol}\n`)
    .join("\n");

  return `# Generated by @solvent/scripts bootstrap — regenerate after every devnet deploy.
# Addresses come from contracts/deployments/solvent-devnet.json.

bind_addr = "0.0.0.0:8080"
rpc_url = "http://127.0.0.1:8545"
chain_id = ${manifest.chain_id}

aqua_address = "${manifest.aqua}"
app_address = "${manifest.router}"

default_fee_bps = 5
block_explorer_url = "http://localhost:5100"
networks = ["Ethereum"]
faucet = true

token_list = "${tokenListPath}"

native_token = "${address(manifest, "WETH")}"
gas_units_per_leg = 150000
binance_ws_url = "wss://stream.binance.com:9443"

${feeds}
usd_stable_pegs = ["${address(manifest, "USDT")}"]

filler = "${manifest.filler}"
permit2 = "${manifest.permit2}"
confirmations = 1
reservation_ttl_secs = 60
decay_window_secs = 60

wallet_state_db = "walletkit.redb"
`;
}

function main(): void {
  const manifest = readManifest();
  const tokenListPath = relative(REPO_ROOT, TOKENS_OUT);

  mkdirSync(dirname(TOKENS_OUT), { recursive: true });
  writeFileSync(TOKENS_OUT, `${JSON.stringify(tokenList(manifest), null, 2)}\n`);
  writeFileSync(CONFIG_OUT, configToml(manifest, tokenListPath));

  console.log(`bootstrap: aqua=${manifest.aqua} app=${manifest.router}`);
  console.log(`bootstrap: wrote ${tokenListPath} (${Object.keys(manifest.tokens).length} tokens)`);
  console.log(`bootstrap: wrote ${relative(REPO_ROOT, CONFIG_OUT)}`);
}

main();
