/**
 * Generate the server's runtime config from the devnet deploy manifest.
 *
 * The deploy script `new`-deploys the Core-6 tokens, so their addresses are whatever the chain
 * assigned — the checked-in `tokens.devnet.json` (mainnet addresses) does not describe a local
 * devnet. Both artifacts below are generated per-deploy and stay untracked.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";

import { readManifest, REPO_ROOT, type Manifest } from "../lib/manifest.ts";

const TOKENS_OUT = resolve(REPO_ROOT, "devnet/generated/tokens.json");
const CONFIG_OUT = resolve(REPO_ROOT, "solvent.toml");
const ENV_OUT = resolve(REPO_ROOT, "devnet/generated/env.sh");

// Anvil's deterministic dev accounts. #0 deploys, so it owns the router and filler; #1 cosigns.
// Publicly known throwaway keys — devnet only, never a real network.
const DEPLOYER_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const COSIGNER_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d";

// Symbol -> token-list tag, mirroring the checked-in list's grouping. Tags are read by people in
// the asset picker, so they are cased as they should appear.
const TAGS: Record<string, string> = {
  WETH: "Majors",
  WBTC: "Majors",
  USDC: "Stables",
  USDT: "Stables",
  DAI: "Stables",
  LINK: "DeFi",
};

// Binance feed symbol -> the devnet token it prices.
const PRICE_FEEDS: Record<string, string> = {
  ETHUSDT: "WETH",
  BTCUSDT: "WBTC",
  USDCUSDT: "USDC",
  LINKUSDT: "LINK",
};

/** Held at $1 instead of tracking a feed: USDT is the quote unit itself, and Binance's DAIUSDT
 *  is a dead pair that reports a zero price. */
const PEGGED = ["USDT", "DAI"];

const NAMES: Record<string, string> = {
  WETH: "Wrapped Ether",
  WBTC: "Wrapped BTC",
  USDC: "USD Coin",
  USDT: "Tether USD",
  DAI: "Dai Stablecoin",
  LINK: "ChainLink Token",
};

function tokenList(manifest: Manifest) {
  return {
    name: "Solvent Devnet",
    version: { major: 1, minor: 0, patch: 0 },
    tokens: Object.entries(manifest.tokens).map(([symbol, token]) => ({
      chainId: manifest.chain_id,
      address: token.address,
      symbol,
      name: NAMES[symbol] ?? symbol,
      decimals: token.decimals,
      tags: [TAGS[symbol] ?? "other"],
    })),
  };
}

function address(manifest: Manifest, symbol: string): string {
  const token = manifest.tokens[symbol];
  if (!token) throw new Error(`manifest has no ${symbol} token`);
  return token.address;
}

function present(manifest: Manifest, symbols: string[]): string[] {
  return symbols.filter((symbol) => manifest.tokens[symbol]);
}

function configToml(manifest: Manifest, tokenListPath: string): string {
  const pegs = present(manifest, PEGGED)
    .map((symbol) => `"${address(manifest, symbol)}"`)
    .join(", ");

  // Every scalar key must precede the first [[price_symbols]] header: in TOML a key written after
  // an array-of-tables header belongs to that table, which silently drops it from the root.
  const feeds = Object.entries(PRICE_FEEDS)
    .filter(([, symbol]) => manifest.tokens[symbol])
    .map(
      ([feed, symbol]) =>
        `[[price_symbols]]\nsymbol = "${feed}"\ntokens = ["${address(manifest, symbol)}"]  # ${symbol}\n`,
    )
    .join("\n");

  return `# Generated by @solvent/scripts bootstrap — regenerate after every devnet deploy.
# Addresses come from contracts/deployments/solvent-devnet.json.

bind_addr = "0.0.0.0:8080"
rpc_url = "http://127.0.0.1:8545"
chain_id = ${manifest.chain_id}

# Required to run the live server, despite being optional in the config type.
database_url = "sqlite:devnet/generated/solvent.db?mode=rwc"

aqua_address = "${manifest.aqua}"
app_address = "${manifest.router}"

default_fee_bps = 5
block_explorer_url = "http://localhost:5100"
networks = ["Ethereum"]
faucet = true

token_list = "${tokenListPath}"

native_token = "${address(manifest, "WETH")}"
gas_units_per_leg = 150000
binance_ws_url = "wss://stream.binance.com:9443"
usd_stable_pegs = [${pegs}]

filler = "${manifest.filler}"
reactor = "${manifest.reactor}"
permit2 = "${manifest.permit2}"
confirmations = 1
reservation_ttl_secs = 60
decay_window_secs = 60

wallet_state_db = "devnet/generated/walletkit.redb"

${feeds}`;
}

function main(): void {
  const manifest = readManifest();
  const tokenListPath = relative(REPO_ROOT, TOKENS_OUT);

  mkdirSync(dirname(TOKENS_OUT), { recursive: true });
  writeFileSync(TOKENS_OUT, `${JSON.stringify(tokenList(manifest), null, 2)}\n`);
  writeFileSync(CONFIG_OUT, configToml(manifest, tokenListPath));
  writeFileSync(
    ENV_OUT,
    `# Signing keys the server reads from the environment. Anvil dev accounts — devnet only.\n` +
      `export SOLVENT_SIGNER_KEY=${DEPLOYER_KEY}\n` +
      `export SOLVENT_COSIGNER_KEY=${COSIGNER_KEY}\n`,
  );

  console.log(`bootstrap: aqua=${manifest.aqua} app=${manifest.router}`);
  console.log(`bootstrap: wrote ${tokenListPath} (${Object.keys(manifest.tokens).length} tokens)`);
  console.log(`bootstrap: wrote ${relative(REPO_ROOT, CONFIG_OUT)}`);
  console.log(`bootstrap: wrote ${relative(REPO_ROOT, ENV_OUT)}`);
}

main();
