//! Differential test: the human-range decoder vs strategies built by `@1inch/swap-vm-sdk`.
//!
//! Corpus: `tests/fixtures/aqua_range_vectors.json` (generated by the study lab's
//! `swapvm-lab/test/gen-range-vectors.test.ts`). Concentrated vectors pin the SDK's raw price
//! bounds; pegged vectors pin the deposit-ratio peg and the `linearWidth`-derived symmetric band.
//! The decoder must reproduce each.

use alloy_primitives::hex;
use serde::Deserialize;
use solvent_core::primitives::registry::{
    decode_strategy, price_range, Curve, CurveSpec, RangeKind,
};

#[derive(Deserialize)]
struct Corpus {
    concentrated: Vec<Concentrated>,
    pegged: Vec<Pegged>,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Concentrated {
    strategy_hex: String,
    lower_price: String,
    upper_price: String,
}

#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
struct Pegged {
    strategy_hex: String,
    dec_lo: u8,
    dec_hi: u8,
    expected_peg: String,
    expected_band_pct: f64,
}

fn curve(strategy_hex: &str) -> Curve {
    let bytes = hex::decode(strategy_hex).expect("hex strategy");
    match decode_strategy(&bytes) {
        CurveSpec::Priceable { curve, .. } => curve,
        other => panic!("SDK strategy not priceable: {other:?} ({strategy_hex})"),
    }
}

fn corpus() -> Corpus {
    serde_json::from_str(include_str!("fixtures/aqua_range_vectors.json")).expect("range corpus")
}

#[test]
fn concentrated_range_matches_the_sdk() {
    for v in corpus().concentrated {
        // The SDK's rawPrice is the base-unit hi-per-lo price; equal decimals + base = lo ⇒ human == raw.
        let r = price_range(&curve(&v.strategy_hex), 18, 18, true);
        assert_eq!(r.kind, RangeKind::Bounded);
        assert_eq!(r.lower_price.as_deref(), Some(v.lower_price.as_str()));
        assert_eq!(r.upper_price.as_deref(), Some(v.upper_price.as_str()));
    }
}

#[test]
fn pegged_range_matches_the_sdk() {
    for v in corpus().pegged {
        let r = price_range(&curve(&v.strategy_hex), v.dec_lo, v.dec_hi, true);
        assert_eq!(r.kind, RangeKind::Peg);
        assert_eq!(r.peg_price.as_deref(), Some(v.expected_peg.as_str()));
        let band = r.below_pct.expect("band");
        assert!(
            (band - v.expected_band_pct).abs() < 1e-9,
            "band {band} vs SDK {}",
            v.expected_band_pct
        );
        assert_eq!(r.above_pct, r.below_pct);
    }
}
