[package]
name = "solvent"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
futures = "0.3"
solvent-core = { path = "../core", features = ["tracing"] }
solvent-adapters = { path = "../adapters" }
alloy = { version = "1", features = [
    "providers",
    "reqwest-rustls-tls",
    "rpc-types-eth",
    "signer-local",
] }
walletkit = { package = "walletkit-rs", git = "https://github.com/21r21a33333/walletkit.git", rev = "3e75a5d2385da13d6ab813104f1e2473860e32cb", default-features = false, features = ["redb"] }
axum = "0.8"
config = { version = "0.15", default-features = false, features = ["toml"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite"] }
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "net"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
