//! The generated OpenAPI document, served at `/v1/openapi.json`. Paths and schemas are collected
//! from the handlers' `#[utoipa::path]` annotations and the `ToSchema` derives, so the document
//! cannot drift from the code.

use axum::Json;
use utoipa::OpenApi;

#[derive(OpenApi)]
#[openapi(
    info(title = "Solvent API", version = "0.1.0"),
    paths(
        crate::http::app::config::config,
        crate::http::app::stats::stats,
        crate::http::app::assets::assets,
        crate::http::app::pools::pools,
        crate::http::app::pools::pool_detail,
        crate::http::app::pools::pool_depth,
        crate::http::app::balances::balances,
        crate::http::app::swap::quote,
        crate::http::app::swap::submit,
        crate::http::app::trades::trades,
        crate::http::app::trades::trade_detail,
        crate::http::app::uniswapx_feed::uniswapx_feed,
        crate::http::app::activity::activity,
        crate::http::app::makers::makers,
        crate::http::app::makers::maker_dashboard,
        crate::http::app::makers::maker_inventory,
        crate::http::app::makers::maker_trades,
        crate::http::app::makers::maker_positions,
        crate::http::app::makers::position_detail,
        crate::http::app::makers::position_depth,
        crate::http::app::makers::position_history,
        crate::http::app::pairs::pairs,
        crate::http::app::pairs::pair_history,
        crate::http::app::positions::preview,
        crate::http::app::rebates::rebates,
        crate::http::app::rebates::rebate_detail,
    ),
    components(schemas(
        crate::http::primitives::Status,
        crate::http::state::AppConfig,
        crate::http::state::Features,
        crate::http::app::stats::Stats,
        solvent_core::asset::Asset,
        solvent_core::asset::Token,
        solvent_core::pool::CurveMix,
        solvent_core::pool::Pool,
        solvent_core::pool::PoolType,
        solvent_core::pool::PoolMaker,
        solvent_core::pool::PoolDetail,
        solvent_core::pool::PoolDepth,
        solvent_core::pool::DepthPoint,
        solvent_core::primitives::pool::Side,
        solvent_core::balances::TokenBalance,
        solvent_core::primitives::amount::Amount,
        solvent_core::primitives::amount::TokenAmount,
        solvent_core::primitives::amount::TokenAmounts,
        solvent_core::quote::QuoteResponse,
        solvent_core::quote::QuoteLeg,
        crate::http::app::swap::QuoteRequest,
        crate::http::app::swap::SwapRequest,
        crate::http::app::swap::SwapResponse,
        solvent_core::primitives::trade::TradeView,
        crate::http::app::uniswapx_feed::UniswapXFeedAssetView,
        crate::http::app::uniswapx_feed::UniswapXFeedOrderView,
        solvent_core::primitives::trade::TradeAction,
        solvent_core::primitives::trade::MakerLeg,
        solvent_core::primitives::trade::MakerTrade,
        crate::http::app::activity::ActivityEvent,
        solvent_core::primitives::maker::Position,
        solvent_core::primitives::maker::PositionHistory,
        solvent_core::primitives::maker::StrategyPrice,
        solvent_core::primitives::maker::PriceRange,
        solvent_core::primitives::maker::PositionBalances,
        solvent_core::primitives::maker::Split,
        solvent_core::primitives::maker::Economics,
        solvent_core::primitives::maker::ActiveStats,
        solvent_core::primitives::maker::MakerSummary,
        solvent_core::primitives::maker::MakerDashboard,
        solvent_core::primitives::maker::MakerPeriod,
        solvent_core::primitives::maker::MakerActivityBucket,
        solvent_core::primitives::maker::MakerKpis,
        solvent_core::primitives::maker::FillShare,
        solvent_core::primitives::maker::InventoryRow,
        solvent_core::primitives::maker::InventoryLeg,
        solvent_core::primitives::maker::PreviewResponse,
        solvent_core::primitives::asset::PairInfo,
        solvent_core::primitives::asset::PairKind,
        solvent_core::primitives::asset::PairWallet,
        solvent_core::primitives::asset::PairPriceHistory,
        solvent_core::primitives::asset::PairPricePoint,
        solvent_core::primitives::asset::PriceHistoryPeriod,
        crate::http::app::positions::PreviewRequest,
        crate::http::app::positions::AmountIn,
        crate::http::app::rebates::RebateStatus,
        crate::http::app::rebates::RebateAllocationView,
        crate::http::app::rebates::RebateWork,
    ))
)]
pub struct ApiDoc;

/// Serve the OpenAPI document as JSON.
pub async fn openapi_json() -> Json<utoipa::openapi::OpenApi> {
    Json(ApiDoc::openapi())
}
