//! The UniswapX V2 normalizer against a fixture generated by the real contract
//! (`contracts/script/GenV2OrderFixture.s.sol`): the decoded `Intent` and, critically, the
//! `orderHash` must match `V2DutchOrderLib.hash` bit-for-bit.

use std::str::FromStr;

use alloy::primitives::{address, b256, Bytes, U256};
use solvent_adapters::ingest::uniswapx::UniswapXV2Normalizer;
use solvent_core::deps::ingest::{NormalizeError, Normalizer};
use solvent_core::primitives::ingest::{AmountCurve, Exclusivity, ProtocolId, RawOrder, Rounding};
use solvent_core::primitives::{ChainId, IntentId};

const PAYLOAD: &str = include_str!("fixtures/uniswapx_v2_order.hex");

fn e18(n: u64) -> U256 {
    U256::from(n) * U256::from(10u64).pow(U256::from(18u64))
}

#[test]
fn normalizes_a_real_v2_order_and_matches_the_contract_hash() {
    let payload = Bytes::from_str(PAYLOAD.trim()).expect("fixture hex");
    let sig = Bytes::from(vec![0xABu8; 65]);
    let raw = RawOrder::new(
        ProtocolId::UniswapXV2,
        ChainId(1),
        payload.clone(),
        sig.clone(),
        1234,
    );

    let intent = UniswapXV2Normalizer
        .normalize(&raw)
        .expect("well-formed order normalizes");

    // orderHash from the real V2DutchOrderLib.hash — the load-bearing assertion.
    assert_eq!(
        intent.id,
        IntentId(b256!(
            "da9f2c83696505972948bd811639b25445d1e10b652ae98dd168fb47ae47c0d1"
        ))
    );
    assert_eq!(intent.protocol, ProtocolId::UniswapXV2);

    // Exact-input order: fixed input, single decaying output.
    assert_eq!(
        intent.input.token,
        address!("6666666666666666666666666666666666666666")
    );
    assert_eq!(intent.input.curve, AmountCurve::scalar(e18(500)));

    assert_eq!(intent.outputs.len(), 1);
    let out = &intent.outputs[0];
    assert_eq!(
        out.token,
        address!("7777777777777777777777777777777777777777")
    );
    assert_eq!(
        out.recipient,
        address!("8888888888888888888888888888888888888888")
    );
    match &out.curve {
        AmountCurve::Linear {
            start,
            end,
            start_time,
            end_time,
            rounding,
        } => {
            assert_eq!(*start, e18(1000));
            assert_eq!(*end, e18(900));
            assert_eq!(*start_time, 1000);
            assert_eq!(*end_time, 1100);
            assert_eq!(*rounding, Rounding::Down);
        }
        other => panic!("expected a decaying output curve, got {other:?}"),
    }

    assert_eq!(intent.deadline, 2000);
    assert_eq!(
        intent.exclusivity,
        Some(Exclusivity {
            filler: address!("5555555555555555555555555555555555555555"),
            ends_at: 1000,
        })
    );
    assert_eq!(
        intent.settler,
        address!("2222222222222222222222222222222222222222")
    );
    assert_eq!(intent.origin_chain, ChainId(1));
    assert_eq!(intent.raw, payload);
    assert_eq!(intent.signature, sig);
    assert_eq!(intent.observed_at, 1234);
}

#[test]
fn rejects_a_malformed_payload() {
    let raw = RawOrder::new(
        ProtocolId::UniswapXV2,
        ChainId(1),
        Bytes::from_static(&[1, 2, 3]),
        Bytes::new(),
        0,
    );
    assert!(matches!(
        UniswapXV2Normalizer.normalize(&raw),
        Err(NormalizeError::Decode(ProtocolId::UniswapXV2))
    ));
}
