//! The UniswapX V2 normalizer end to end: a cosigned order, as the builder mints it and the
//! deployed reactor would accept it, becomes an `Intent` whose fields carry the order's terms.
//!
//! Contract fidelity of the order hash and the two signing digests is pinned separately, against a
//! fixture generated by `contracts/script/GenV2OrderFixture.s.sol` — see the codec's own tests. That
//! fixture carries no cosignature, so it is not an order this normalizer will admit.

use alloy::primitives::{address, Address, Bytes, B256, U256};
use alloy::signers::local::PrivateKeySigner;
use solvent_adapters::ingest::uniswapx::{OrderSpec, SignedOrderBuilder, UniswapXV2Normalizer};
use solvent_core::deps::ingest::{NormalizeError, Normalizer};
use solvent_core::primitives::ingest::{
    AmountCurve, Exclusivity, OrderSource, ProtocolId, RawOrder,
};
use solvent_core::primitives::ChainId;

const PERMIT2: Address = address!("000000000022D473030F116dDEE9F6B43aC78BA3");
const REACTOR: Address = address!("2222222222222222222222222222222222222222");
const EXCLUSIVE_FILLER: Address = address!("5555555555555555555555555555555555555555");

fn key(byte: u8) -> PrivateKeySigner {
    PrivateKeySigner::from_bytes(&B256::from([byte; 32])).expect("valid test key")
}

fn e18(n: u64) -> U256 {
    U256::from(n) * U256::from(10u64).pow(U256::from(18u64))
}

fn spec() -> OrderSpec {
    OrderSpec {
        reactor: REACTOR,
        nonce: U256::from(42u64),
        deadline: 2000,
        input_token: address!("6666666666666666666666666666666666666666"),
        input_start: e18(500),
        input_end: e18(500),
        output_token: address!("7777777777777777777777777777777777777777"),
        output_start: e18(1000),
        output_end: e18(900),
        recipient: address!("8888888888888888888888888888888888888888"),
        decay_start: 1000,
        decay_end: 1100,
        exclusive_filler: EXCLUSIVE_FILLER,
        exclusivity_override_bps: 100,
    }
}

#[test]
fn normalizes_a_cosigned_v2_order() {
    let builder = SignedOrderBuilder::new(PERMIT2, 1, key(0x11), key(0x22));
    let raw = builder.build(&spec(), 1234);
    let normalizer = UniswapXV2Normalizer::new(REACTOR, vec![key(0x22).address()]);

    let intent = normalizer
        .normalize(&raw)
        .expect("well-formed order normalizes");
    let spec = spec();

    assert_eq!(intent.protocol, ProtocolId::UniswapXV2);
    assert_eq!(intent.swapper, key(0x11).address());
    assert_eq!(intent.settler, REACTOR);
    assert_eq!(intent.origin_chain, ChainId(1));
    assert_eq!(intent.deadline, spec.deadline);
    assert_eq!(intent.observed_at, 1234);
    assert_eq!(intent.raw, raw.payload);
    assert_eq!(intent.signature, raw.signature);

    // Exact-input order: fixed input, single decaying output.
    assert_eq!(intent.input.token, spec.input_token);
    assert_eq!(intent.input.curve, AmountCurve::scalar(spec.input_start));

    assert_eq!(intent.outputs.len(), 1);
    let out = &intent.outputs[0];
    assert_eq!(out.token, spec.output_token);
    assert_eq!(out.recipient, spec.recipient);
    assert_eq!(
        out.curve,
        AmountCurve::dutch(
            spec.output_start,
            spec.output_end,
            spec.decay_start,
            spec.decay_end
        )
    );

    assert_eq!(
        intent.exclusivity,
        Some(Exclusivity::new(EXCLUSIVE_FILLER, spec.decay_start, 100))
    );
}

/// The window carries the toll a non-exclusive filler pays, so the decision path can price taking
/// the order early instead of treating it as unfillable.
#[test]
fn carries_the_exclusivity_override() {
    let builder = SignedOrderBuilder::new(PERMIT2, 1, key(0x11), key(0x22));
    let strict = OrderSpec {
        exclusivity_override_bps: 0,
        ..spec()
    };
    let raw = builder.build(&strict, 0);
    let normalizer = UniswapXV2Normalizer::new(REACTOR, vec![key(0x22).address()]);
    let intent = normalizer.normalize(&raw).expect("normalizes");
    let exclusivity = intent.exclusivity.expect("exclusive");
    assert_eq!(exclusivity.override_bps, 0);
    assert!(!exclusivity.grants_rights_to(Address::repeat_byte(0xAB), exclusivity.ends_at));
}

#[test]
fn rejects_a_malformed_payload() {
    let raw = RawOrder::new(
        ProtocolId::UniswapXV2,
        ChainId(1),
        Bytes::from_static(&[1, 2, 3]),
        Bytes::new(),
        0,
        OrderSource::UniswapX,
    );
    let normalizer = UniswapXV2Normalizer::new(REACTOR, vec![key(0x22).address()]);
    assert!(matches!(
        normalizer.normalize(&raw),
        Err(NormalizeError::Decode(ProtocolId::UniswapXV2))
    ));
}
